[ci] Speed up checking out the code (#6429)
# Why

`Checkout code` step in CI takes definitely too much time and is kinda unpredictable - the longest waiting time I encountered was almost 9 minutes! Unfortunately I cannot find it right now 😅

## Some stats from before:

<img width="680" alt="Screenshot 2019-12-04 at 11 28 32" src="https://user-images.githubusercontent.com/1714764/70138895-8ecba080-1691-11ea-8ecf-cf6fb2adb72b.png">
<img width="680" alt="Screenshot 2019-12-04 at 11 33 14" src="https://user-images.githubusercontent.com/1714764/70138901-95f2ae80-1691-11ea-9a02-ada793089b4e.png">
<img width="680" alt="Screenshot 2019-12-04 at 11 34 42" src="https://user-images.githubusercontent.com/1714764/70138906-97bc7200-1691-11ea-89d0-27f57edd1e3b.png">
<img width="680" alt="Screenshot 2019-12-04 at 11 35 21" src="https://user-images.githubusercontent.com/1714764/70138956-bc184e80-1691-11ea-9166-130539718fca.png">

# How

`git clone` operation can be faster by doing a shallow copy - then we download only the last commit and fetch a few previous ones if we need to compare them with master (to check whether we can halt a job if nothing has changed).

## After these changes:

<img width="680" alt="Screenshot 2019-12-04 at 11 38 27" src="https://user-images.githubusercontent.com/1714764/70138972-c5a1b680-1691-11ea-9b0f-89a5a9beac56.png">
<img width="680" alt="Screenshot 2019-12-04 at 12 14 15" src="https://user-images.githubusercontent.com/1714764/70138978-c8041080-1691-11ea-9ff2-491fdaeb5f0a.png">

# Test Plan

All CI jobs in this PR pass.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,6 +3,7 @@ version: 2.1
 orbs:
   job-status-change: expo/job-status-change@1.0.11
   slack-job-status-notification: expo/slack-job-status-notification@1.0.6
+  shallow-checkout: expo/shallow-checkout@1.0.1
 
 commands:
   conditionally_halt:
@@ -37,7 +38,15 @@ commands:
               exit 0
             fi
 
-            BASE_COMMIT=$(git merge-base HEAD remotes/origin/"${ROOT_BRANCH}")
+            echo " ▶️  Searching for the base commit of ${CIRCLE_BRANCH} and ${ROOT_BRANCH} ..."
+
+            # merge-base can exit with code 1, so we ignore when it fails.
+            BASE_COMMIT=$(git merge-base $CIRCLE_BRANCH $ROOT_BRANCH || :)
+            while [ -z $BASE_COMMIT ]; do
+              git fetch --deepen=2 origin $CIRCLE_BRANCH $ROOT_BRANCH
+              BASE_COMMIT=$(git merge-base $CIRCLE_BRANCH $ROOT_BRANCH || :)
+            done
+
             echo "Checking for changes in branch ${CIRCLE_BRANCH}"
             echo " - Excluding << parameters.exclude >>"
             echo " - Requiring << parameters.requireOneOf >>"
@@ -93,7 +102,15 @@ commands:
               exit 0
             fi
 
-            BASE_COMMIT=$(git merge-base HEAD remotes/origin/"${ROOT_BRANCH}")
+            echo " ▶️  Searching for the base commit of ${CIRCLE_BRANCH} and ${ROOT_BRANCH} ..."
+
+            # merge-base can exit with code 1, so we ignore when it fails.
+            BASE_COMMIT=$(git merge-base $CIRCLE_BRANCH $ROOT_BRANCH || :)
+            while [ -z $BASE_COMMIT ]; do
+              git fetch --deepen=2 origin $CIRCLE_BRANCH $ROOT_BRANCH
+              BASE_COMMIT=$(git merge-base $CIRCLE_BRANCH $ROOT_BRANCH || :)
+            done
+
             echo "Checking for changes in branch ${CIRCLE_BRANCH}"
             echo " - Required << parameters.requireOneOf >>"
             echo " - Git repository root at ${CIRCLE_WORKING_DIRECTORY}"
@@ -122,6 +139,7 @@ commands:
             else
               echo 'user-halt' > "$CIRCLE_INTERNAL_SCRATCH/HALT_TASK"
             fi
+
   install_nix:
     steps:
       - run: curl https://nixos.org/releases/nix/nix-2.1.2/install | bash -s -- --no-daemon
@@ -158,7 +176,7 @@ commands:
       - run: echo -e "[whitelist]\nprefix = [ \"$HOME\" ]" > ~/.config/direnv/config.toml
       - run: echo 'eval "$(direnv export bash)"' >> ~/.bash_profile
       - run: echo '--frozen-lockfile true' >> ~/.yarnrc
-      - checkout
+      - shallow-checkout/checkout
       - job-status-change/prepare
   decrypt_secrets_if_possible:
     steps:
@@ -270,7 +288,7 @@ executors:
       - image: lnl7/nix:2.1.2
     # Symlink to the readline-enabled bash which is the default command of the container
     shell: /run/current-system/sw/bin/bash -leo pipefail
-    working_directory: ~/expo
+    working_directory: /root/expo
     environment:
       # fastlane complains if these are not set
       LANG: en_US.UTF-8
@@ -287,7 +305,7 @@ executors:
     docker:
       - image: circleci/node:latest-browsers
     shell: /bin/bash -leo pipefail
-    working_directory: ~/expo
+    working_directory: /home/circleci/expo
     resource_class: small
     environment:
       USER: circleci
@@ -297,6 +315,7 @@ executors:
     working_directory: /Users/distiller/project
     shell: /bin/bash -leo pipefail
     environment:
+      # Homebrew settings
       HOMEBREW_NO_INSTALL_CLEANUP: 1
       HOMEBREW_NO_AUTO_UPDATE: 1
       # fastlane complains if these are not set
