Add github workflow output message

diff --git a/.github/workflows/android-unit-tests.yml b/.github/workflows/android-unit-tests.yml
--- a/.github/workflows/android-unit-tests.yml
+++ b/.github/workflows/android-unit-tests.yml
@@ -60,7 +60,7 @@ jobs:
         env:
           ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/19.2.5345600/
         working-directory: android
-        run: ./gradlew spotlessCheck
+        run: ./gradlew spotlessCheck || echo '::error Spotless lint failed. Run `./gradlew spotlessApply` to automatically fix formatting.'
       - name: Run native Android unit tests
         env:
           ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/19.2.5345600/
