[ci] Move spotless ktlint check before tests

diff --git a/.github/workflows/android-unit-tests.yml b/.github/workflows/android-unit-tests.yml
--- a/.github/workflows/android-unit-tests.yml
+++ b/.github/workflows/android-unit-tests.yml
@@ -48,6 +48,11 @@ jobs:
           key: ${{ runner.os }}-gradle-${{ hashFiles('android/*.gradle*') }}
           restore-keys: |
             ${{ runner.os }}-gradle-
+      - name: Run Spotless lint check
+        env:
+          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/19.2.5345600/
+        working-directory: android
+        run: ./gradlew spotlessCheck || { echo '::error Spotless lint failed. Run `./gradlew spotlessApply` to automatically fix formatting.' && exit 1; }
       - uses: actions/cache@v2
         id: cache-android-ndk
         with:
@@ -70,8 +75,3 @@ jobs:
         with:
           name: test-results
           path: packages/**/build/test-results/**/*xml
-      - name: Run Spotless lint check
-        env:
-          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/19.2.5345600/
-        working-directory: android
-        run: ./gradlew spotlessCheck || { echo '::error Spotless lint failed. Run `./gradlew spotlessApply` to automatically fix formatting.' && exit 1; }
