[ci] Add Spotless to android-unit-tests.yml (#46856)
# Why
The `spotless apply` step used to run during `android-unit-test` on
`expo-go` but was removed in this PR:
https://github.com/expo/expo/pull/46729

# How 
Adds the `spotless apply` step which is executed in
`apps/bare-expo/android`. Also, fixed existing lint errors.

# Test Plan
Green CI ✅

diff --git a/.github/workflows/android-unit-tests.yml b/.github/workflows/android-unit-tests.yml
--- a/.github/workflows/android-unit-tests.yml
+++ b/.github/workflows/android-unit-tests.yml
@@ -62,6 +62,9 @@ jobs:
         run: echo "$(pwd)/bin" >> $GITHUB_PATH
       - name: 📦 Install node modules
         run: pnpm install --frozen-lockfile
+      - name: 💅 Run Spotless lint check
+        working-directory: apps/bare-expo/android
+        run: ./gradlew spotlessCheck || { echo '::error Spotless lint failed. Run `./gradlew spotlessApply` from `apps/bare-expo/android` to automatically fix formatting.' && exit 1; }
       - name: 🎸 Run native Android unit tests
         if: always()
         timeout-minutes: 30
