[brownfield][test] setup e2e maestro tests for ios

diff --git a/.github/workflows/test-suite-brownfield-isolated.yml b/.github/workflows/test-suite-brownfield-isolated.yml
--- a/.github/workflows/test-suite-brownfield-isolated.yml
+++ b/.github/workflows/test-suite-brownfield-isolated.yml
@@ -84,6 +84,8 @@ jobs:
           react-native-gradle-downloads: 'true'
       - name: 🧶 Install workspace node modules
         run: yarn install --frozen-lockfile
+      - name: 👷 Build Expo CLI
+        run: yarn workspace @expo/cli prepare
       - name: 🤖 Build and publish Android artifacts (apps/brownfield-tester/expo-app)
         run: |
           npx expo prebuild --clean -p android
@@ -109,5 +111,65 @@ jobs:
           channel: '#expo-android'
           author_name: E2E Test Suite for Expo Brownfield
 
-  # TODO(pmleczek): Add iOS job
-  # ios-e2e:
+  ios-e2e:
+    runs-on: macos-15
+    needs: detect-platform-for-e2e
+    if: needs.detect-platform-for-e2e.outputs.should_run_ios == 'true'
+    strategy:
+      fail-fast: false
+      matrix:
+        build-type: [debug, release]
+    steps:
+      - name: 👀 Checkout
+        uses: actions/checkout@v5
+      - name: 🏗️ Setup Bun
+        uses: oven-sh/setup-bun@v2
+        with:
+          # Version `1.x` fails due to https://github.com/oven-sh/setup-bun/issues/37
+          # TODO(cedric): swap `latest` back once the issue is resolved
+          bun-version: latest
+      - name: 🔨 Switch to Xcode 26.2
+        run: sudo xcode-select --switch /Applications/Xcode_26.2.app
+      - name: 🍺 Install required tools
+        run: |
+          brew install watchman || true
+      - name: ➕ Add `bin` to GITHUB_PATH
+        run: echo "$(pwd)/bin" >> $GITHUB_PATH
+      - name: 💎 Setup Ruby and install gems
+        uses: ruby/setup-ruby@v1
+        with:
+          bundler-cache: true
+          ruby-version: 3.2.2
+      - name: 💎 Install xcodeproj gem
+        run: gem install xcodeproj
+      - name: ♻️ Restore caches
+        uses: ./.github/actions/expo-caches
+        id: expo-caches
+        with:
+          yarn-workspace: 'true'
+          yarn-tools: 'true'
+          bare-expo-pods: 'true'
+      - name: 🧶 Install node modules in root dir
+        run: yarn install --frozen-lockfile
+      - name: 👷 Build Expo CLI
+        run: yarn workspace @expo/cli prepare
+      - name: 🍏 Build iOS artifacts (apps/brownfield-tester/expo-app)
+        run: |
+          npx expo prebuild --clean -p ios
+          npx expo-brownfield build:ios --${{ matrix.build-type }} --verbose -a $GITHUB_WORKSPACE/artifacts
+        working-directory: apps/brownfield-tester/expo-app
+      - name: 🔨 Add XCFrameworks to SwiftUI project
+        run: ruby packages/expo-brownfield/e2e/scripts/add_xcframeworks.rb
+      - name: 🍺 Install Maestro
+        run: |
+          curl -Ls "https://get.maestro.mobile.dev" | bash
+          echo "${HOME}/.maestro/bin" >> $GITHUB_PATH
+      - name: 🧪 Run e2e tests (isolated brownfield)
+        run: ./packages/expo-brownfield/e2e/scripts/run-e2e-ios.sh
+      - name: 🔔 Notify on Slack
+        uses: ./.github/actions/slack-notify
+        if: failure() && (github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
+        with:
+          webhook: ${{ secrets.slack_webhook_ios }}
+          channel: '#expo-ios'
+          author_name: E2E Test Suite for Expo Brownfield
